### ISSUE TITLE
Not saving correctly

### ISSUE THREAD

**Issue by taminar** [corbennett/probeLocator#10]
The html is associated with the wrong mouse, should be impossible to save to the wrong folder. So far all the sessions I have looked at have the same wrong mouse associated with them.

**Comment by greggheller** [comment]
This seems to be an issue with the HTML only, while the saved NPZ has the correct points. Not sure how we can investigate or what we can do about this.

**Comment by greggheller** [comment]
It is necessary to save the notebook to get the html to update and save correctly
