### ISSUE TITLE
Local warping?

### ISSUE THREAD

**Issue by greggheller** [corbennett/probeLocator#5]
@jsiegle has proposed that we add the ability to use the algorithm that hes using for OPT alignment that applies some local warping. I think it  would be worth putting in to see what it looks like but should leave the current algorithm for cases where local warping doesn't make sense

**Comment by jsiegle** [comment]
This is the code I'm using, but translated to the 2D case (requires the [vtk](https://pypi.org/project/vtk/) Python library):

```Python
transform = vtk.vtkThinPlateSplineTransform()

source_points = vtk.vtkPoints() # points from insertion image
target_points = vtk.vtkPoints() # points on ISI map

# putting control points in the corners seems to help:
for x in [0,1024]:
    for y in [0,1024]:
            source_points.InsertNextPoint([x,y])
            target_points.InsertNextPoint([x,y])

# now add the landmarks we manually clicked on:
for i in range(source_landmarks.shape[0]):
    if source_landmarks[i,0] > -1 and target_landmarks[i,0] > -1:
        source_points.InsertNextPoint(source_landmarks[i,:])
    
for i in range(target_landmarks.shape[0]):
    if source_landmarks[i,0] > -1 and target_landmarks[i,0] > -1:
        target_points.InsertNextPoint(target_landmarks[i,:])

transform.SetSourceLandmarks(source_points)
transform.SetTargetLandmarks(target_points)
transform.Update()
```

Then, you can use  `x,y = transform.TransformFloatPoint([xi,yi])` to warp points on the insertion image to points on the ISI map.

**Comment by corbennett** [comment]
Now implemented. Activate by

localWarp = True

otherwise, only the perspective transform is used. Not sure which option is best. I'm a little wary of making local deformations when shifts in the vasculature might not reflect local deformations of the underlying brain. Do we think the brain is deforming in this way? I suppose swelling could cause this to some degree.
